---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: docker
  become: true
  roles:
    - docker_install

- hosts: wazuh
  become: true
  roles:
    - wazuh_container_install
